apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodie-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moodie
  template:
    metadata:
      labels:
        app: moodie
    spec:
      containers:
      - name: moodie-container
        image: puneeth773/moodie:v1.0.3
        ports:
        - containerPort: 5000
        env:
        - name: VIRTUAL_ENV
          value: "/opt/venv"
        - name: PATH
          value: "/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
---
apiVersion: v1
kind: Service
metadata:
  name: moodie-service
spec:
  selector:
    app: moodie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31838
  type: NodePort
