apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'moodie'
        static_configs:
          - targets: ['moodie-service:5000']
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints