apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodie-backend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moodie-backend
  template:
    metadata:
      labels:
        app: moodie-backend
    spec:
      containers:
      - name: moodie-backend-container
        image: moodie:latest
        imagePullPolicy: Never  # Use local image for testing
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: moodie-backend-service
  namespace: default
spec:
  selector:
    app: moodie-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31838
  type: NodePort
